[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
verbosity = 5

fs_permissions = [{ access = "read", path = "./script" }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
optimizer = true
optimizer_runs = 200
